INSERT INTO USER_INFORMATION(USER_ID, EMAIL, IS_ACCOUNT_NON_EXPIRED, IS_ACCOUNT_NON_LOCKED, IS_CREDENTIALS_NON_EXPIRED,
IS_ENABLE,PASSWORD,USER_NAME) VALUES(1, 'SHUBHAM.GADEKAR99@GMAIL.COM', 1, 1, 1, 1, '$2a$12$48tDDEmw/jCP0I1Cp0w6Ju41jPJmY5fIziq.8ys9xb6mxkkgd5tqi', 'shubham'),
(2, 'SHUBHAM.GADEKAR99@GMAIL.COM', 1, 1, 1, 1, '$2a$12$l95R.5gaOiIwlY7T.CLYf.2LNaJA4sXOxxu/0pXsrT3r3mqwb7TI2', 'rushabh');

INSERT INTO ROLES(ROLE_ID,ROLE_NAME) VALUES(1,'USER'), (2,'ADMIN');

INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES(1,1),(1,2),(2,1);