spring:
  application:
    name: secure-me-gateway
  profiles:
    active:
    - dev
  config:
    import:
    - optional:configserver:http://config:config@localhost:8888
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
      - id: SECURE-ME-AUTHENTICATION
        uri: lb://SECURE-ME-AUTHENTICATION
        predicates:
        - Path=/authentication/**
      - id: SECURE-ME-METADATA
        uri: lb://SECURE-ME-AUTHENTICATION
        predicates:
        - Path=/metadata/**
          
          
    
